"""
Centralized prompt text and schema descriptions used across the Caïssa server.
"""

from .agents import (
    CLASSIC_AGENT_PROMPT,
    REINFORCED_AGENT_PROMPT,
    BUILDER_AGENT_PROMPT,
    VERIFIER_JSON_PROMPT,
    VERIFIER_FIX_PROMPT,
)
from .selectors import PIPELINE_MAIN_PROMPT, PIPELINE_VERIFIER_PROMPT
from .tools import CYPHER_GENERATION_TEMPLATE
from .schemas import (
    POSITION_SCHEMA_DESCRIPTION,
    RELATION_SCHEMA_DESCRIPTION,
    MOVE_FEATURE_SCHEMA_DESCRIPTION,
)

__all__ = [
    "CLASSIC_AGENT_PROMPT",
    "REINFORCED_AGENT_PROMPT",
    "BUILDER_AGENT_PROMPT",
    "VERIFIER_JSON_PROMPT",
    "VERIFIER_FIX_PROMPT",
    "PIPELINE_MAIN_PROMPT",
    "PIPELINE_VERIFIER_PROMPT",
    "CYPHER_GENERATION_TEMPLATE",
    "POSITION_SCHEMA_DESCRIPTION",
    "RELATION_SCHEMA_DESCRIPTION",
    "MOVE_FEATURE_SCHEMA_DESCRIPTION",
]
